2018-10-23 00:28:37,026 ERROR: Exception on /user/falk [GET] [in /Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/main/routes.py", line 42, in user
    return render_template('user.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/templates/user.html", line 13, in block "app_content"
    <p><a href="{{ url_for('edit_profile') }}">Edit your profile</a></p>
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit_profile'. Did you mean 'main.edit_profile' instead?
2018-10-23 00:29:21,171 INFO: Microblog startup [in /Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/__init__.py:69]
2018-10-23 00:30:50,548 ERROR: Exception on /auth/reset_password_request [POST] [in /Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/auth/routes.py", line 54, in reset_password_request
    send_password_reset_email(user)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/auth/email.py", line 10, in send_password_reset_email
    text_body=render_template('email/reset_password.txt', user=user, token=token),
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/templates/email/reset_password.txt", line 5, in top-level template code
    {{ url_for('reset_password', token=token, _external=True) }}
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2018-10-23 00:32:39,942 INFO: Microblog startup [in /Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/__init__.py:69]
